import { Restaurant } from './store'

export const mockRestaurants: Restaurant[] = [
  {
    id: 'burger-house',
    name: 'Burger House',
    description: 'Сочные бургеры и хрустящие картошки',
    image: '/images/main.jpeg',
    rating: 4.8,
    deliveryTime: '25-35 мин',
    deliveryFee: 150,
    minimumOrder: 500,
    cuisine: ['Американская', 'Бургеры'],
    isOpen: true,
    address: 'ул. Советская, 25',
    phone: '+7 (987) 123-45-67',
    totalReviews: 324,
    workingHours: [
      { day: 'Понедельник', open: '10:00', close: '22:00', isClosed: false },
      { day: 'Вторник', open: '10:00', close: '22:00', isClosed: false },
      { day: 'Среда', open: '10:00', close: '22:00', isClosed: false },
      { day: 'Четверг', open: '10:00', close: '22:00', isClosed: false },
      { day: 'Пятница', open: '10:00', close: '22:00', isClosed: false },
      { day: 'Суббота', open: '10:00', close: '22:00', isClosed: false },
      { day: 'Воскресенье', open: '11:00', close: '22:00', isClosed: false },
    ],
    reviews: [
      {
        id: '1',
        user_name: 'Анна К.',
        rating: 5,
        comment: 'Отличные бургеры! Очень быстрая доставка',
        date: '15.01.2025',
      },
      {
        id: '2',
        user_name: 'Михаил С.',
        rating: 4,
        comment: 'Вкусно, но могли бы добавить больше соуса',
        date: '14.01.2025',
      },
      {
        id: '3',
        user_name: 'Елена П.',
        rating: 5,
        comment: 'Лучшие бургеры в городе! Рекомендую всем',
        date: '13.01.2025',
      },
    ],
    menu: [
      {
        id: 'angus-burger',
        name: 'Ангус Бургер',
        description: 'Сочная котлета из говядины Ангус, свежие овощи, фирменный соус',
        price: 450,
        image: '/images/menu/angusburger.jpg',
        category: 'Бургеры',
        restaurant_id: 'burger-house',
        ingredients: ['Говядина Ангус', 'Булочка', 'Салат', 'Помидор', 'Лук', 'Сыр', 'Соус'],
        available: true,
      },
      {
        id: 'chicken-burger',
        name: 'Чикен Бургер',
        description: 'Хрустящая куриная котлета, свежие овощи, пикантный соус',
        price: 380,
        image: '/images/menu/chickenburger.jpg',
        category: 'Бургеры',
        restaurant_id: 'burger-house',
        ingredients: ['Куриное филе', 'Булочка', 'Салат', 'Помидор', 'Огурец', 'Майонез'],
        available: true,
      },
      {
        id: 'cheese-burger',
        name: 'Чизбургер',
        description: 'Классический бургер с расплавленным сыром и говяжьей котлетой',
        price: 320,
        image: '/images/menu/cheeseburger.jpg',
        category: 'Бургеры',
        restaurant_id: 'burger-house',
        ingredients: ['Говядина', 'Сыр чеддер', 'Булочка', 'Салат', 'Лук', 'Кетчуп'],
        available: true,
      },
      {
        id: 'caesar-salad',
        name: 'Салат Цезарь',
        description: 'Классический салат с курицей, сыром пармезан и соусом цезарь',
        price: 280,
        image: '/images/menu/fries.jpg',
        category: 'Салаты',
        restaurant_id: 'burger-house',
        ingredients: ['Салат романо', 'Куриное филе', 'Сыр пармезан', 'Сухарики', 'Соус цезарь'],
        available: true,
      },
      {
        id: 'fries',
        name: 'Картофель фри',
        description: 'Хрустящий золотистый картофель с морской солью',
        price: 180,
        image: '/images/menu/fries.jpg',
        category: 'Фастфуд',
        restaurant_id: 'burger-house',
        ingredients: ['Картофель', 'Растительное масло', 'Морская соль'],
        available: true,
      },
      {
        id: 'nuggets',
        name: 'Куриные наггетсы',
        description: 'Нежные кусочки куриного филе в хрустящей панировке',
        price: 220,
        image: '/images/menu/nuggets.jpg',
        category: 'Фастфуд',
        restaurant_id: 'burger-house',
        ingredients: ['Куриное филе', 'Панировка', 'Специи'],
        available: true,
      },
      {
        id: 'cola',
        name: 'Кока-Кола',
        description: 'Освежающий напиток 0.5л',
        price: 120,
        image: '/images/menu/cola.jpg',
        category: 'Напитки',
        restaurant_id: 'burger-house',
        available: true,
      },
      {
        id: 'fanta',
        name: 'Фанта',
        description: 'Апельсиновый газированный напиток 0.5л',
        price: 120,
        image: '/images/menu/fanta.jpg',
        category: 'Напитки',
        restaurant_id: 'burger-house',
        available: true,
      },
    ],
  },
  {
    id: 'pizza-palace',
    name: 'Pizza Palace',
    description: 'Аутентичная итальянская пицца на тонком тесте',
    image: '/images/about.jpg',
    rating: 4.6,
    deliveryTime: '30-40 мин',
    deliveryFee: 200,
    minimumOrder: 600,
    cuisine: ['Итальянская', 'Пицца'],
    isOpen: true,
    address: 'ул. Ленина, 45',
    phone: '+7 (987) 234-56-78',
    totalReviews: 256,
    workingHours: [
      { day: 'Понедельник', open: '11:00', close: '22:00', isClosed: false },
      { day: 'Вторник', open: '11:00', close: '22:00', isClosed: false },
      { day: 'Среда', open: '11:00', close: '22:00', isClosed: false },
      { day: 'Четверг', open: '11:00', close: '22:00', isClosed: false },
      { day: 'Пятница', open: '11:00', close: '23:00', isClosed: false },
      { day: 'Суббота', open: '11:00', close: '23:00', isClosed: false },
      { day: 'Воскресенье', open: '12:00', close: '21:00', isClosed: false },
    ],
    reviews: [
      {
        id: '4',
        user_name: 'Дмитрий В.',
        rating: 5,
        comment: 'Настоящая итальянская пицца! Очень вкусно',
        date: '16.01.2025',
      },
      {
        id: '5',
        user_name: 'Ольга М.',
        rating: 4,
        comment: 'Хорошая пицца, но доставка немного задержалась',
        date: '17.01.2025',
      },
    ],
    menu: [
      {
        id: 'margherita-pizza',
        name: 'Маргарита',
        description: 'Классическая пицца с моцареллой, томатами и базиликом',
        price: 520,
        image: '/images/menu/margaritapizza.jpg',
        category: 'Пицца',
        restaurant_id: 'pizza-palace',
        ingredients: ['Тесто', 'Томатный соус', 'Моцарелла', 'Базилик', 'Оливковое масло'],
        available: true,
      },
      {
        id: 'pepperoni-pizza',
        name: 'Пепперони',
        description: 'Пицца с острой салями пепперони и сыром моцарелла',
        price: 650,
        image: '/images/menu/pepperonipizza.jpg',
        category: 'Пицца',
        restaurant_id: 'pizza-palace',
        ingredients: ['Тесто', 'Томатный соус', 'Моцарелла', 'Пепперони'],
        available: true,
      },
      {
        id: 'caprese-salad',
        name: 'Капрезе',
        description: 'Итальянский салат с моцареллой и томатами',
        price: 350,
        image: '/images/menu/margaritapizza.jpg',
        category: 'Салаты',
        restaurant_id: 'pizza-palace',
        ingredients: ['Моцарелла', 'Томаты', 'Базилик', 'Оливковое масло'],
        available: true,
      },
    ],
  },
  {
    id: 'taco-fiesta',
    name: 'Taco Fiesta',
    description: 'Мексиканская кухня с острыми специями',
    image: '/images/workwithus.jpeg',
    rating: 4.4,
    deliveryTime: '20-30 мин',
    deliveryFee: 180,
    minimumOrder: 400,
    cuisine: ['Мексиканская', 'Тако'],
    isOpen: true,
    address: 'ул. Пушкина, 15',
    phone: '+7 (987) 345-67-89',
    totalReviews: 189,
    workingHours: [
      { day: 'Понедельник', open: '12:00', close: '22:00', isClosed: false },
      { day: 'Вторник', open: '12:00', close: '22:00', isClosed: false },
      { day: 'Среда', open: '12:00', close: '22:00', isClosed: false },
      { day: 'Четверг', open: '12:00', close: '22:00', isClosed: false },
      { day: 'Пятница', open: '12:00', close: '23:00', isClosed: false },
      { day: 'Суббота', open: '12:00', close: '23:00', isClosed: false },
      { day: 'Воскресенье', open: '00:00', close: '00:00', isClosed: true },
    ],
    reviews: [
      {
        id: '6',
        user_name: 'Игорь Л.',
        rating: 4,
        comment: 'Острые и вкусные тако! Понравилось',
        date: '18.01.2025',
      },
    ],
    menu: [
      {
        id: 'beef-taco',
        name: 'Тако с говядиной',
        description: 'Хрустящая тортилья с говядиной, овощами и острым соусом',
        price: 180,
        image: '/images/menu/taco.jpg',
        category: 'Шаурма',
        restaurant_id: 'taco-fiesta',
        ingredients: ['Тортилья', 'Говядина', 'Лук', 'Перец', 'Острый соус', 'Сыр'],
        available: true,
      },
      {
        id: 'chicken-kebab',
        name: 'Куриный кебаб',
        description: 'Сочное куриное мясо в пите с овощами и соусом',
        price: 280,
        image: '/images/menu/kebab.jpg',
        category: 'Шаурма',
        restaurant_id: 'taco-fiesta',
        ingredients: ['Пита', 'Куриное филе', 'Огурцы', 'Помидоры', 'Соус цацики'],
        available: true,
      },
      {
        id: 'sandwich',
        name: 'Сэндвич клаб',
        description: 'Многослойный сэндвич с курицей, беконом и овощами',
        price: 350,
        image: '/images/menu/sandwich.jpg',
        category: 'Фастфуд',
        restaurant_id: 'taco-fiesta',
        ingredients: ['Хлеб', 'Курица', 'Бекон', 'Салат', 'Помидор', 'Майонез'],
        available: true,
      },
      {
        id: 'guacamole',
        name: 'Гуакамоле',
        description: 'Традиционная мексиканская закуска из авокадо',
        price: 220,
        image: '/images/menu/taco.jpg',
        category: 'Закуски',
        restaurant_id: 'taco-fiesta',
        ingredients: ['Авокадо', 'Лимон', 'Лук', 'Перец чили', 'Кинза'],
        available: true,
      },
    ],
  },
  {
    id: 'sushi-master',
    name: 'Sushi Master',
    description: 'Свежие роллы и суши от японского мастера',
    image: '/images/main.jpeg',
    rating: 4.7,
    deliveryTime: '40-50 мин',
    deliveryFee: 250,
    minimumOrder: 800,
    cuisine: ['Японская', 'Суши'],
    isOpen: true,
    address: 'ул. Мира, 78',
    phone: '+7 (987) 456-78-90',
    totalReviews: 298,
    workingHours: [
      { day: 'Понедельник', open: '11:00', close: '23:00', isClosed: false },
      { day: 'Вторник', open: '11:00', close: '23:00', isClosed: false },
      { day: 'Среда', open: '11:00', close: '23:00', isClosed: false },
      { day: 'Четверг', open: '11:00', close: '23:00', isClosed: false },
      { day: 'Пятница', open: '11:00', close: '24:00', isClosed: false },
      { day: 'Суббота', open: '11:00', close: '24:00', isClosed: false },
      { day: 'Воскресенье', open: '12:00', close: '22:00', isClosed: false },
    ],
    reviews: [
      {
        id: '7',
        user_name: 'Алексей Н.',
        rating: 5,
        comment: 'Лучшие роллы в городе! Всегда свежие и вкусные',
        date: '19.01.2025',
      },
      {
        id: '8',
        user_name: 'Мария К.',
        rating: 4,
        comment: 'Отличное качество, но цены высоковаты',
        date: '18.01.2025',
      },
    ],
    menu: [
      {
        id: 'philadelphia-roll',
        name: 'Филадельфия',
        description: 'Классический ролл с лососем, сливочным сыром и огурцом',
        price: 420,
        image: '/images/menu/margaritapizza.jpg',
        category: 'Роллы',
        restaurant_id: 'sushi-master',
        ingredients: ['Лосось', 'Сливочный сыр', 'Огурец', 'Нори', 'Рис'],
        available: true,
      },
      {
        id: 'california-roll',
        name: 'Калифорния',
        description: 'Ролл с крабом, авокадо и икрой тобико',
        price: 380,
        image: '/images/menu/margaritapizza.jpg',
        category: 'Роллы',
        restaurant_id: 'sushi-master',
        ingredients: ['Краб', 'Авокадо', 'Икра тобико', 'Нори', 'Рис'],
        available: true,
      },
      {
        id: 'dragon-roll',
        name: 'Дракон',
        description: 'Горячий ролл с угрем, авокадо и унаги соусом',
        price: 520,
        image: '/images/menu/margaritapizza.jpg',
        category: 'Роллы',
        restaurant_id: 'sushi-master',
        ingredients: ['Угорь', 'Авокадо', 'Сливочный сыр', 'Унаги соус', 'Рис'],
        available: true,
      },
      {
        id: 'miso-soup',
        name: 'Мисо суп',
        description: 'Традиционный японский суп с тофу и водорослями',
        price: 180,
        image: '/images/menu/margaritapizza.jpg',
        category: 'Закуски',
        restaurant_id: 'sushi-master',
        ingredients: ['Мисо паста', 'Тофу', 'Водоросли', 'Лук зеленый'],
        available: true,
      },
      {
        id: 'green-tea',
        name: 'Зеленый чай',
        description: 'Ароматный японский зеленый чай',
        price: 150,
        image: '/images/menu/margaritapizza.jpg',
        category: 'Напитки',
        restaurant_id: 'sushi-master',
        available: true,
      },
    ],
  },
]

export const categories = [
  { id: 'all', name: 'Все', icon: 'utensils' },
  { id: 'Пицца', name: 'Пицца', icon: 'pizza-slice' },
  { id: 'Бургеры', name: 'Бургеры', icon: 'hamburger' },
  { id: 'Роллы', name: 'Роллы', icon: 'fish' },
  { id: 'Шаурма', name: 'Шаурма', icon: 'utensils' },
  { id: 'Фастфуд', name: 'Фастфуд', icon: 'cookie-bite' },
  { id: 'Салаты', name: 'Салаты', icon: 'leaf' },
  { id: 'Закуски', name: 'Закуски', icon: 'pepper-hot' },
  { id: 'Напитки', name: 'Напитки', icon: 'glass-water' },
]

export const cuisineTypes = [
  'Все',
  'Американская',
  'Итальянская',
  'Мексиканская',
  'Азиатская',
  'Русская',
  'Европейская',
] 